export interface AIProvider { generate(prompt: string): Promise<string>; }

class MockProvider implements AIProvider {
  async generate(prompt: string) {
    return [
      "# Draft generated by AI Website Factory",
      "",
      "> No AI provider is configured yet, so this deterministic draft was generated instead.",
      "",
      "## Generation brief",
      "",
      "~~~text",
      prompt,
      "~~~"
    ].join("\n");
  }
}

class OpenAIProvider implements AIProvider {
  constructor(private apiKey: string, private model: string) {}

  async generate(prompt: string) {
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + this.apiKey
      },
      body: JSON.stringify({
        model: this.model,
        input: prompt,
        temperature: 0.4
      })
    });

    if (!response.ok) {
      const message = await response.text();
      throw new Error("AI generation failed: " + response.status + " " + message);
    }

    const data = await response.json() as {
      output_text?: string;
      output?: Array<{ content?: Array<{ type?: string; text?: string }> }>;
    };

    if (data.output_text?.trim()) return data.output_text.trim();

    const text = data.output
      ?.flatMap(item => item.content ?? [])
      .filter(item => item.type === "output_text")
      .map(item => item.text ?? "")
      .join("\n")
      .trim();

    if (!text) throw new Error("AI provider returned no text.");
    return text;
  }
}

export function getAIProvider(): AIProvider {
  const provider = process.env.AI_PROVIDER || "mock";
  const apiKey = process.env.AI_API_KEY;

  if (provider === "openai" && apiKey) {
    return new OpenAIProvider(apiKey, process.env.AI_MODEL || "gpt-5.4-mini");
  }

  return new MockProvider();
}
