export interface AIProvider { generate(prompt: string): Promise<string>; }
class MockProvider implements AIProvider {
  async generate(prompt: string) {
    return ["# Draft generated by AI Website Factory","","> AI provider is not configured yet. This deterministic draft confirms that the generation pipeline is working.","","## Generation brief","","~~~text",prompt,"~~~","","## Next step","","Configure a server-side AI provider and replace this mock implementation for production-quality generation."].join("\n");
  }
}
/** Provider boundary. Keep API keys on the server. */
export function getAIProvider(): AIProvider { return new MockProvider(); }
